#!/usr/bin/env bash
# One-shot production bootstrap for a fresh Ubuntu server.
#
# Run it from INSIDE the cloned repo:
#   sudo bash setup.sh
#
# It will:
#   1. install Docker + the compose plugin (if missing),
#   2. create .env from .env.production.example, generating a strong AUTH_SECRET,
#      a Postgres password, and VAPID push keys, and asking for your APP_HOST,
#   3. build and start the whole stack (Caddy fetches TLS automatically),
#   4. print the one command left: creating your owner login.
#
# Re-running is safe: an existing .env is never overwritten.
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Construction ERP setup"

# --- 1. Docker ---------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker..."
  curl -fsSL https://get.docker.com | sh
else
  echo "==> Docker already installed."
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' plugin not available. Install Docker Compose v2." >&2
  exit 1
fi

# --- 2. .env -----------------------------------------------------------------
if [ -f .env ]; then
  echo "==> .env already exists — keeping your existing secrets."
else
  echo "==> Creating .env"
  read -r -p "Enter APP_HOST (e.g. 203.0.113.10.sslip.io or erp.yourcompany.com): " APP_HOST
  read -r -p "Enter ACME email for cert notices (optional, press Enter to skip): " ACME_EMAIL
  read -r -p "Enter your Anthropic API key for AI features (optional, press Enter to skip): " ANTHROPIC_API_KEY

  AUTH_SECRET="$(openssl rand -base64 48)"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"

  echo "==> Generating VAPID push keys..."
  VAPID_JSON="$(docker run --rm node:20-bookworm-slim sh -c 'npx --yes web-push generate-vapid-keys --json')"
  VAPID_PUBLIC_KEY="$(printf '%s' "$VAPID_JSON" | grep -oP '"publicKey":"\K[^"]+')"
  VAPID_PRIVATE_KEY="$(printf '%s' "$VAPID_JSON" | grep -oP '"privateKey":"\K[^"]+')"

  cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret.
NODE_ENV=production
APP_HOST=${APP_HOST}
ACME_EMAIL=${ACME_EMAIL}

POSTGRES_USER=erp
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=construction_erp
DATABASE_URL=postgresql://erp:${POSTGRES_PASSWORD}@postgres:5432/construction_erp

AUTH_SECRET=${AUTH_SECRET}

STORAGE_DRIVER=local
STORAGE_DIR=/app/storage

TRUSTED_IP_HEADER=x-real-ip
DAY_CLOSE_TZ_OFFSET_MINUTES=330

VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
VAPID_SUBJECT=mailto:${ACME_EMAIL:-admin@example.com}

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
EOF
  chmod 600 .env
  echo "==> .env written (permissions 600)."
fi

# --- 3. Build & start --------------------------------------------------------
echo "==> Building and starting the stack (first build takes a while)..."
docker compose -f docker-compose.prod.yml up -d --build

echo ""
echo "======================================================================"
echo " Stack is up. Caddy is fetching your HTTPS certificate now."
echo ""
echo " LAST STEP — create your owner login:"
echo "   docker compose -f docker-compose.prod.yml run --rm worker \\"
echo "     pnpm tsx scripts/bootstrap-owner.ts"
echo ""
echo " Then open:  https://$(grep '^APP_HOST=' .env | cut -d= -f2-)"
echo "======================================================================"
